<?php

namespace AppBundle\Repository;

/**
 * comment_respRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class comment_respRepository extends \Doctrine\ORM\EntityRepository
{
}
