<?php

namespace AppBundle\Repository;

/**
 * eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function loadEventById($id)
    {
        return $this->createQueryBuilder('u')
            ->where('u.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function deleteEvent($id_event){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $query = $qb->delete('AppBundle:Event', 'p')
            ->where('p.id = :id')
            ->setParameter('id', $id_event)
            ->getQuery();
        $query->execute();
    }
}
