<?php

namespace AppBundle\Repository;

/**
 * followerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class followerRepository extends \Doctrine\ORM\EntityRepository
{
}
