<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function listNotificationOnArray($array_idseguidores,$offset = 0, $max = 20){
        $seguidores = '('. implode($array_idseguidores,',') . ')';
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n 
                FROM AppBundle:Notification n
                WHERE n.user in ' .$seguidores.'
                 ORDER BY n.id DESC'
            )
            ->setFirstResult($offset)
            ->setMaxResults($max)
            ->getResult();
    }
}
